name: Test the action

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_action:
    runs-on: ubuntu-latest
    name: A job to test the action
    steps:
    - name: Checkout code
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

    - name: Execute action
      id: run
      uses: ./
      with:
        filename: ./.github/workflows/info.xml

    - name: Get the result
      run: |
        echo -e "Versions :\n${{ steps.run.outputs.versions }}"
        echo -e "Available PHP :\n${{ steps.run.outputs.php-available }}"
        echo -e "Branches :\n${{ steps.run.outputs.branches }}"
        echo -e "Matrix :\n${{ steps.run.outputs.matrix }}"
